[package]
name = "lunaris-client"
version = "0.1.0"
edition = "2024"

[dependencies]
lunaris-common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
anyhow = "1"
rustyline = "17.0.2"
comfy-table = "7"
